ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS host_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS setup_complete BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS accepting_emergencies BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS emergency_note TEXT NOT NULL DEFAULT '';
